server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG

spring:
  jpa:
    show-sql: true
    hidernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enable: true
  datasource:
    url: jdbc:h2:mem:testdb
  messages:
    basename: messages
  security:
    user:
      name: spamperson
      password: spamperson

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  management:
    endpoint:
      web:
        exposure:
          include: "*"

